# Generated by Django 5.2.7 on 2025-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rubric_options_alter_bb_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='subscribed_rubrics',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='main.subrubric', verbose_name='Категории писем'),
        ),
    ]
